import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../../components/Navbar'
import Partners from '../../components/Partners'
import Footer2 from '../../components/Footer2'


export default function Enterprise() {
  return (
    <>
      <Head>
        <title>Enterprise Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/pen.ico" />
      </Head>

     <Navbar/>
     <div className="page-title-area item-bg1">
      <div className="container">
        <div className="page-title-content">
          <h2>Enterprise Management Solutions</h2>
          <ul>
            <li>
              <a href="../index.html">Home</a>
            </li>
            <li>Enterprise Management Solutions</li>
          </ul>
        </div>
      </div>
    </div>
    <section className="service-details-area ptb-100">
      <div className="container">
        <div className="row">
          <div className="col-lg-8">
            <div className="service-details-wrap">
              <div className="service-img">
                <Image
                  src="/img/sftdev.png"
                  alt="Image"
                  width={856}
                    height={475}
                />
              </div>
              <h3>Enterprise Management Solutions</h3>
              <p>
              Our Enterprise Software Solutions aim to improve effeciency,productivity and business functionality regardless of the size or the nature of your business.
              </p>
              <h3>Vehicle tracking</h3>
              <p>
              Vehicle tracking is monitoring the location, movements, status, and behavior of a vehicle or fleet of vehicles. This is achieved 
through a combination of a GPS (GNSS) receiver and an electronic device (usually comprising a GSM GPRS modem or SMS sender) 
installed in each vehicle, communicating with the user (dispatching, emergency, or coordinating unit) and PC-based or web-based 
software.
              </p>
              <h3>Trailer tracking</h3>
              <p>
              Tracking the movements and position of an articulated vehicle`s trailer unit, through the use of a location unit fitted to the trailer and 
a method of returning the position data via a mobile communication network, IoT (Internet of things), or geostationary satellite 
communications, for use through either PC- or web-based software.
              </p>
              <h3>Mobile data</h3>
              <p>
              Use of wireless data communications using radio waves to send and receive real-time computer data to, from, and between devices 
used by field-based personnel. These devices can be fitted solely for use while in the vehicle (Fixed Data Terminal) or for use in and 
out of the vehicle (Mobile Data Terminal).
              </p>
              <h3>Intelligent vehicle technologies</h3>
              <p>
              Telematics comprises electronic, electromechanical, and electromagnetic devices — usually silicon micromachined components
operating in conjunction with computer-controlled devices and radio transceivers to provide precision repeatability functions (such as 
in robotics artificial intelligence systems) and emergency warning validation performance reconstruction.
              </p>
            
            </div>
            
          </div>
          
          <div className="col-lg-4">
            <div className="service-sidebar-area">
              <div className="service-list">
                <h3 className="service-details-title">Services</h3>
                <ul>
                  <li>
                    <Link href="/it-security/1/">
                    <a >
                      IT Security
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/it-consultancy/1">
                    <a >
                      IT Consultancy
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/enterprise-management/1">
                    <a >
                      Enterprise Managment
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/business-intelligence/1">
                    <a >
                      Business Intelligence
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                </ul>
              </div>
              <div className="service-list">
                <h3 className="service-details-title">Contact Info</h3>
                <ul>
                  <li>
                  0779 249 673 / 0787 490 605
                    <i className="bx bx-phone-call bx-rotate-270" />
                  </li>
                  <li>
                    <a
                      href="#"
                      className="__cf_email__"
                      data-cfemail="bdd5d8d1d1d2fdd7c8d0cdc593ded2d0"
                    >
                     info@piasysug.com 
                    </a>
                    <i className="bx bx-envelope" />
                  </li>
                  <li>
                  3 Floor, Shumuk Building
                    <i className="bx bx-location-plus" />
                  </li>
                  <li>
                    9:00 AM - 5:00 PM
                    <i className="bx bx-time" />
                  </li>
                </ul>
              </div>  
            </div>
          </div>
        </div>
      </div>
    </section>
    <Partners/>
    <Footer2/>

     </>
  )
}
