import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer2 from '../components/Footer2'



export default function About() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pen.ico" />
      </Head>

     <Navbar/>
     <div className="page-title-area item-bg1">
      <div className="container">
        <div className="page-title-content">
          <h2>About Us</h2>
          <ul>
            <li>
              <Link href="/">
              <a >Home</a>
              </Link>
            </li>
            <li>About</li>
          </ul>
        </div>
      </div>
    </div>
    <section className="service-details-area ptb-100">
      <div className="container">
        <div className="row">
          <div className="col-lg-8">
            <div className="service-details-wrap">
              <div className="service-img">
                <Image
                  src="/img/about.png"
                  alt="Image"
                  width={856}
                  height={478}
                />
              </div>
              <h3>About Us</h3>
              <p>
              Pencil systems Uganda Limited boasts a plethora of highly 
trained and creative, skilled, multi-talented, and experienced 
software Developers with a unique blend of mobile, enterprise 
programming, and design prowess; the team has been behind 
conceptualizing, designing, and developing applications, is a 
privately held IT firm that deals in software development, 
web design and development, mobile application
development, hosting, digital media management, Value
Added services (VAS) and Advanced Credit (ACS), and 
IT consultancy Services in Uganda.
              </p>    
            </div>
            
          </div>
          
          <div className="col-lg-4">
            <div className="service-sidebar-area">
              <div className="service-list">
                <h3 className="service-details-title">Services</h3>
                <ul>
                  <li>
                    <Link href="/it-security/1/">
                    <a >
                      IT Security
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/it-consultancy/1">
                    <a >
                      IT Consultancy
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/enterprise-management/1">
                    <a >
                      Enterprise Managment
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/business-intelligence/1">
                    <a >
                      Business Intelligence
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                  </li>
                </ul>
              </div>
              <div className="service-list">
                <h3 className="service-details-title">Contact Info</h3>
                <ul>
                  <li>
                  0779 249 673 / 0787 490 605
                    <i className="bx bx-phone-call bx-rotate-270" />
                  </li>
                  <li>
                    <a
                      href="#"
                      className="__cf_email__"
                      data-cfemail="bdd5d8d1d1d2fdd7c8d0cdc593ded2d0"
                    >
                     info@piasysug.com 
                    </a>
                    <i className="bx bx-envelope" />
                  </li>
                  <li>
                  3 Floor, Shumuk Building
                    <i className="bx bx-location-plus" />
                  </li>
                  <li>
                    9:00 AM - 5:00 PM
                    <i className="bx bx-time" />
                  </li>
                </ul>
              </div>  
            </div>
          </div>
        </div>
      </div>
    </section>
    <Footer2/>

     </>
  )
}
