import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Culture from "../components/Culture";

import Services from "../components/Services";

import Partners from "../components/Partners";
import Footer2 from "../components/Footer2";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pencil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/pen.ico" />
      </Head>

      <Navbar />
      <Hero />

      <Culture />

      <Services />

      <Partners />

      <Footer2 />
    </>
  );
}
