import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '../../components/Navbar'
import Footer2 from '../../components/Footer2'


export default function Consultancy() {
  return (
    <>
      <Head>
        <title>IT Consultancy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/pen.ico" />
      </Head>

     <Navbar/>
     <div className="page-title-area item-bg1">
      <div className="container">
        <div className="page-title-content">
          <h2>IT Consultancy and Outsourcing</h2>
          <ul>
            <li>
              <a href="../index.html">Home</a>
            </li>
            <li>IT Consultancy Details</li>
          </ul>
        </div>
      </div>
    </div>
    <section className="service-details-area ptb-100">
      <div className="container">
        <div className="row">
          <div className="col-lg-8">
            <div className="service-details-wrap">
              <div className="service-img">
                <Image
                  src="/img/sftdev.png"
                  alt="Image"
                  width={856}
                    height={475}
                />
              </div>
              <h3>IT Consultancy</h3>
              <p>
              We develop enterprise web, mobile, and desktop 
applications using the latest technologies
through a holistic, immersive, agile process.
              </p>
              <h3>IT Outsourcing</h3>
              <p>
              Designed for companies with 50-1000 employees, our IT outsourcing solution enables you to hand over full responsibility for your end 
users and your infrastructure to us. Our 24/7/365 service desk will deliver 1st, 2nd, and 3rd line support to your end users and look after 
your infrastructure, to your defined hours and standard SLAs, whilst making sure the outcomes are fully aligned to your business
objectives. With Pencil`s outsourcing solution you can also tap into an experienced team of IT consultants, software engineers, cloud 
architects, and project managers for IT consultancy or additional support to implement significant IT infrastructure and application 
transformation projects faster.
              </p>
            
            </div>
            
          </div>
          
          <div className="col-lg-4">
            <div className="service-sidebar-area">
              <div className="service-list">
                <h3 className="service-details-title">Services</h3>
                <ul>
                  <li>
                    <Link href="/it-security/1/">
                    <a >
                      IT Security
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/it-consultancy/1">
                    <a >
                      IT Consultancy
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/enterprise-management/1">
                    <a >
                      Enterprise Managment
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                  <li>
                    <Link href="/business-intelligence/1">
                    <a >
                      Business Intelligence
                      <i className="bx bx-check" />
                    </a>
                    </Link>
                    
                  </li>
                </ul>
              </div>
              <div className="service-list">
                <h3 className="service-details-title">Contact Info</h3>
                <ul>
                  <li>
                  0779 249 673 / 0787 490 605
                    <i className="bx bx-phone-call bx-rotate-270" />
                  </li>
                  <li>
                    <a
                      href="#"
                      className="__cf_email__"
                      data-cfemail="bdd5d8d1d1d2fdd7c8d0cdc593ded2d0"
                    >
                     info@piasysug.com 
                    </a>
                    <i className="bx bx-envelope" />
                  </li>
                  <li>
                  3 Floor, Shumuk Building
                    <i className="bx bx-location-plus" />
                  </li>
                  <li>
                    9:00 AM - 5:00 PM
                    <i className="bx bx-time" />
                  </li>
                </ul>
              </div>  
            </div>
          </div>
        </div>
      </div>
    </section>
    <Footer2/>

     </>
  )
}
